<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pengunjung".
 *
 * @property integer $id
 * @property string $foto
 * @property integer $pakai_masker
 * @property double $tegangan_piezoelektrik
 * @property string $timestamp
 * @property string $aliasModel
 */
abstract class Pengunjung extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pengunjung';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['foto', 'pakai_masker', 'tegangan_piezoelektrik', 'timestamp'], 'required'],
            [['pakai_masker'], 'integer'],
            [['tegangan_piezoelektrik'], 'number'],
            [['timestamp'], 'safe'],
            [['foto'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'foto' => 'Foto',
            'pakai_masker' => 'Pakai Masker',
            'tegangan_piezoelektrik' => 'Tegangan Piezoelektrik',
            'timestamp' => 'Timestamp',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'pakai_masker' => '0:tidak pakai masker;1:pakai masker',
        ]);
    }




}
